services:
  - type: web
    name: double-talk
    env: elixir
    plan: free
    buildCommand: ./build.sh
    startCommand: _build/prod/rel/double_talk/bin/double_talk start
    autoDeploy: true
    envVars:
      - key: ELIXIR_VERSION
        value: 1.18.4
      - key: ERLANG_VERSION
        value: 28.0.2
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: "true"
      - key: POOL_SIZE
        value: "10"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        sync: false
